ALTER TABLE answer
    DROP CONSTRAINT fk_answer_on_user;

ALTER TABLE job_application
    DROP CONSTRAINT fk_job_application_on_user;

CREATE TABLE candidate
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     INTEGER                                  NOT NULL,
    first_name  VARCHAR(255),
    middle_name VARCHAR(255),
    last_name   VARCHAR(255),
    CONSTRAINT pk_candidate PRIMARY KEY (id)
);

ALTER TABLE answer
    ADD candidate_id INTEGER;

ALTER TABLE company_review
    ADD candidate_id INTEGER;

ALTER TABLE job_application
    ADD candidate_id INTEGER;

ALTER TABLE bookmark
    ADD candidate_id INTEGER;

ALTER TABLE company
    ADD user_id INTEGER;

ALTER TABLE candidate
    ADD CONSTRAINT uc_candidate_user UNIQUE (user_id);

ALTER TABLE company
    ADD CONSTRAINT uc_company_user UNIQUE (user_id);

ALTER TABLE questionnaire
    ADD CONSTRAINT uc_questionnaire_job UNIQUE (job_id);

ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_CANDIDATE FOREIGN KEY (candidate_id) REFERENCES candidate (id);

ALTER TABLE candidate
    ADD CONSTRAINT FK_CANDIDATE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE company_review
    ADD CONSTRAINT FK_COMPANYREVIEW_ON_CANDIDATE FOREIGN KEY (candidate_id) REFERENCES candidate (id);

ALTER TABLE company_review
    ADD CONSTRAINT FK_COMPANYREVIEW_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE company
    ADD CONSTRAINT FK_COMPANY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE job_application
    ADD CONSTRAINT FK_JOB_APPLICATION_ON_CANDIDATE FOREIGN KEY (candidate_id) REFERENCES candidate (id);

CREATE INDEX idx_candidate_on_job_application ON job_application (candidate_id);

ALTER TABLE questionnaire
    ADD CONSTRAINT FK_QUESTIONNAIRE_ON_JOB FOREIGN KEY (job_id) REFERENCES job (id);

ALTER TABLE answer
    DROP COLUMN user_id;

ALTER TABLE company_review
    DROP COLUMN user_id;

ALTER TABLE job_application
    DROP COLUMN user_id;

ALTER TABLE bookmark
    DROP COLUMN user_id;

ALTER TABLE question
    ALTER COLUMN type SET NOT NULL;