CREATE TABLE company
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                             NOT NULL,
    description TEXT,
    CONSTRAINT pk_company PRIMARY KEY (id)
);