CREATE TABLE post
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(255)                             NOT NULL,
    content TEXT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);