CREATE TABLE users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(100)                             NOT NULL,
    password VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_user_email UNIQUE (email);

CREATE INDEX idx_user_on_email ON users (email);