CREATE TABLE job_application
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_id  INTEGER,
    user_id INTEGER,
    CONSTRAINT pk_job_application PRIMARY KEY (id)
);

ALTER TABLE job_application
    ADD CONSTRAINT FK_JOB_APPLICATION_ON_JOB FOREIGN KEY (job_id) REFERENCES job (id);

CREATE INDEX idx_job_on_job_application ON job_application (job_id);

ALTER TABLE job_application
    ADD CONSTRAINT FK_JOB_APPLICATION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_user_on_job_application ON job_application (user_id);