CREATE TYPE question_type AS ENUM ('TEXT', 'SINGLE_SELECT', 'MULTI_SELECT');

CREATE TABLE question
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(255),
    type question_type,
    CONSTRAINT pk_question PRIMARY KEY (id)
);

CREATE TABLE questionnaire
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description TEXT,
    job_id      INTEGER                                  NOT NULL,
    CONSTRAINT pk_questionnaire PRIMARY KEY (id)
);