CREATE TYPE question_type AS ENUM ('TEXT', 'SINGLE_SELECT', 'MULTI_SELECT');

CREATE TABLE question
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(255),
    type question_type,
    CONSTRAINT pk_question PRIMARY KEY (id)
);
