CREATE TABLE questionnaire_question
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    questionnaire_id INTEGER,
    question_id      INTEGER,
    display_order    INTEGER,
    CONSTRAINT pk_questionnairequestion PRIMARY KEY (id)
);

ALTER TABLE questionnaire_question
    ADD CONSTRAINT uc_66f9fcbbe72dbafa95296e7b5 UNIQUE (questionnaire_id, "display_order");

ALTER TABLE questionnaire_question
    ADD CONSTRAINT FK_QUESTIONNAIREQUESTION_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

ALTER TABLE questionnaire_question
    ADD CONSTRAINT FK_QUESTIONNAIREQUESTION_ON_QUESTIONNAIRE FOREIGN KEY (questionnaire_id) REFERENCES questionnaire (id);